// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQC64fpkEX0SJOTLkDTOdit7sEz7VFxlo',
    appId: '1:425852838224:web:8346eca59e8b4a2de98c55',
    messagingSenderId: '425852838224',
    projectId: 'assignment-2-af294',
    authDomain: 'assignment-2-af294.firebaseapp.com',
    storageBucket: 'assignment-2-af294.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmip9d52j88RGhNRD-Fu08OxPTan3dBD8',
    appId: '1:425852838224:android:777714b431d541d7e98c55',
    messagingSenderId: '425852838224',
    projectId: 'assignment-2-af294',
    storageBucket: 'assignment-2-af294.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDskJXvVy7vsHBwaZTYZRRYS5qD98OPF4o',
    appId: '1:425852838224:ios:b61adea7e9d62af9e98c55',
    messagingSenderId: '425852838224',
    projectId: 'assignment-2-af294',
    storageBucket: 'assignment-2-af294.firebasestorage.app',
    iosBundleId: 'com.example.assig2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDskJXvVy7vsHBwaZTYZRRYS5qD98OPF4o',
    appId: '1:425852838224:ios:b61adea7e9d62af9e98c55',
    messagingSenderId: '425852838224',
    projectId: 'assignment-2-af294',
    storageBucket: 'assignment-2-af294.firebasestorage.app',
    iosBundleId: 'com.example.assig2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQC64fpkEX0SJOTLkDTOdit7sEz7VFxlo',
    appId: '1:425852838224:web:c3ff71d6b419acc8e98c55',
    messagingSenderId: '425852838224',
    projectId: 'assignment-2-af294',
    authDomain: 'assignment-2-af294.firebaseapp.com',
    storageBucket: 'assignment-2-af294.firebasestorage.app',
  );
}
